version: "3.9"

services:
  web-scrape-notifier:
    container_name: web-scrape-notifier
    image: web-scrape-notifier:latest
    #restart: always
    tty: true
    networks:
      - frontend

networks:
  frontend:
    name: web-scrape-notifier-net