version: "3.9"

services:
  web-scrape-notifier:
    container_name: web-scrape-notifier
    image: web-scrape-notifier:latest
    tty: true
    volumes:
      - type: bind
        source: ./list.csv
        target: /app/list.csv
      - type: bind
        source: ./result.csv
        target: /app/result.csv
